### ISSUE TITLE
Error when using 'wizzard'

### ISSUE THREAD

**Issue by FScociety** [jasonacox/tinytuya#19]
After typing the: api key, secret, deviceId and region.
tiny python gives some python error:
`Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tinytuya/__main__.py", line 48, in <module>
    tinytuya.wizard(color)
  File "/usr/local/lib/python3.9/site-packages/tinytuya/__init__.py", line 1548, in wizard
    uid = response_dict['result']['uid']
KeyError: 'result'`

**Comment by MaveriQ** [comment]
I am running into the same problem. Did you find a solution @FScociety

**Comment by jasonacox** [comment]
Hi @MaveriQ - a few things to check...

This is a step that is easy to miss on the [iot.tuya.com](iot.tuya.com) setup: "Verify under Cloud Development -> select your project -> API Setting that the following API groups have status "Open": Authorization management, Device Management and Device Control - <-- this was raised in issue #20  if you want more info.

Some are reporting that additional settings may be needed - covered here: https://github.com/jasonacox/tuyapower/issues/10
