### ISSUE TITLE
TinyTuya error

### ISSUE THREAD

**Issue by grampasso-lento** [jasonacox/tinytuya#195]
Hi, after configuring the Tuya account and website (all my devices are listed there) i am running °python -m tinytuya wizard -nocolor° but I get the following output: 

Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\lib\site-packages\tinytuya\__main__.py", line 64, in <module>
    wizard.wizard(color=color, forcescan=force)
  File "C:\Python39\lib\site-packages\tinytuya\wizard.py", line 223, in wizard
    tuyadevices = cloud.filter_devices( json_data['result'], ip_list )
KeyError: 'result'

Also, running "python -m tinytuya scan" I only get 2 of my devices listed there.
Any help?
Thanks in advance.
Giovanni

**Comment by uzlonewolf** [comment]
I was able to reproduce this with a correct key and secret, but wrong region and/or device id.  Double-check to make sure both the Region and Device ID are correct.  I'll see if we can detect this like we do for bad keys/secrets and add a better error message when encountered.

**Comment by uzlonewolf** [comment]
That "ablilty" is directly from Tuya's servers, there is nothing we can do about it.

Are you sure those devices are linked to your developer account?  The Region must also match what is set in your developer account.  The only way to get that backtrace is if Tuya's servers are rejecting the device list request.
