### ISSUE TITLE
Another JSONDecodeError

### ISSUE THREAD

**Issue by burgas1** [jasonacox/tinytuya#21]
Hi
I have similar problem with a bulb. tinytuya on RPi Zero. Python 3.7.3
3 equal bulbs. 2 of them I can read just fine. 

```
TinyTuya (Tuya device scanner) [1.1.3]

Scanning on UDP ports 6666 and 6667 for devices (15 retries)...

3.1 Device Found [Valid payload]: 192.168.0.115
    ID = 37800275840d8e54d1d2, Product ID = keyneruwsdethu7u, Version = 3.1
    Status: {'1': False, '9': 0, '18': 0, '19': 0, '20': 2344, '21': 1, '22': 748, '23': 32838, '24': 22222, '25': 935}
3.3 Device Found [Valid payload]: 192.168.0.109
    ID = 8052770184f3ebeec5b1, Product ID = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
3.3 Device Found [Valid payload]: 192.168.0.189
    ID = 01147546600194dd1765, Product ID = keyjcr45yfptp7h7, Version = 3.3
    No Stats - Device Key required to poll for status
3.3 Device Found [Valid payload]: 192.168.0.161
    ID = 80527701ecfabc47dfac, Product ID = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
3.3 Device Found [Valid payload]: 192.168.0.138
    ID = 8052770184f3ebf633b5, Product ID = keyj979nf3q3theh, Version = 3.3
    No Stats - Device Key required to poll for status
                    
Scan Complete!  Found 5 devices.
```
```
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    get_tuya_data_test('80527701ecfabc47dfac', '192.168.0.161', '6af642384da9f2d1')
  File "/root/tee/tee/data.py", line 262, in get_tuya_data_test
    d.set_version(3.3)
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/__init__.py", line 891, in set_version
    status = self.status()
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/__init__.py", line 589, in status
    result = json.loads(result)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
def get_tuya_data_test(tuya_id, ip_addr, tuya_key):
    
        d = tinytuya.BulbDevice(tuya_id, ip_addr, tuya_key)
        d.set_version(3.3)
        data = d.status()
        print(data)
```

_Originally posted by @burgas1 in https://github.com/jasonacox/tinytuya/issues/4#issuecomment-762930600_

**Comment by jasonacox** [comment]
Additional error checking and retry logic has been added to the v1.2.x version.  I recommend you upgrade and try again.

```
pip install --upgrade tinytuya
```
