### ISSUE TITLE
Can't get .status() from switch

### ISSUE THREAD

**Issue by k-0** [jasonacox/tinytuya#3]
Hi,

i can get the status from my 10 lamps, but when I try to get a status from a switch, i get the following error. This is my code:
```
a = tinytuya.OutletDevice('here_is_my_key', '192.168.178.46', 'secret_key_here')
a.set_version(3.3)
data =  a.status()
print(data)

```
And this error occurs:
```
Traceback (most recent call last):
  File "tuya.py", line 89, in <module>
    data =  a.status()
  File "/home/pi/tinytuya/tinytuya/__init__.py", line 405, in status
    result = json.loads(result)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jasonacox** [comment]
It is having trouble with the JSON payload coming back from the switch.  It could be an encryption problem or just a bad JSON format.  Try updating to TinyTuya v1.0.4:
```
python3 -m pip install --upgrade tinytuya
```
and then run the network scan function to see if the switch shows up:
```
python3 -m tinytuya
```

**Comment by k-0** [comment]
I updated from v1.0.3 to v.1.0.4, but still the same problem.

`python3 -m tinytuya`
shows the device correctly (with both versions).

**Comment by jasonacox** [comment]
There seems to be some strange behavior with some devices that have a 22 character IDs.  Try adding `device22` to the initialization for dev_type:

```
a = tinytuya.OutletDevice('here_is_my_key', '192.168.178.46', 'secret_key_here', 'device22')
a.set_version(3.3)
data =  a.status()
print(data)
```

**Comment by k-0** [comment]
I tried adding `device22` and now I get the following error:
```
root@raspberrypi:/home/pi/tinytuya/tinytuya# cd ../ && python3 tuya.py
Traceback (most recent call last):
  File "tuya.py", line 89, in <module>
    data =  a.status()
  File "/home/pi/tinytuya/tinytuya/__init__.py", line 371, in status
    payload = self.generate_payload(DP_QUERY)
  File "/home/pi/tinytuya/tinytuya/__init__.py", line 324, in generate_payload
    json_data['dps'] = self.dpsUsed
AttributeError: 'OutletDevice' object has no attribute 'dpsUsed'
```

**Comment by jasonacox** [comment]
Oops!  Try sending a DPS requested value:

```
a = tinytuya.OutletDevice('here_is_my_key', '192.168.178.46', 'secret_key_here', 'device22')
a.set_version(3.3)
a.set_dpsUsed({"1": None})
data =  a.status()
print(data)
```

Some of the device22 types have different lists of available dps values.  I need to add a feature to scan these for us. If the above works, your device is the most common.  If not, it will require a bit more work to figure it out.

**Comment by k-0** [comment]
Now it works!
Thank you!
