### ISSUE TITLE
Could not find a suitable TLS CA certificate bundle, invalid path: 0

### ISSUE THREAD

**Issue by billonariosh** [jasonacox/tinytuya#450]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\project\SMARTHOME\tinytuya-master\tinytuya\__main__.py", line 76, in <module>
    wizard.wizard(color=color, retries=retries, forcescan=force, quicklist=assume_yes)
  File "D:\project\SMARTHOME\tinytuya-master\tinytuya\wizard.py", line 157, in wizard
    cloud = tinytuya.Cloud( **config )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\SMARTHOME\tinytuya-master\tinytuya\Cloud.py", line 117, in __init__
    self._gettoken()
  File "D:\project\SMARTHOME\tinytuya-master\tinytuya\Cloud.py", line 261, in _gettoken
    response_dict = self._tuyaplatform('token?grant_type=1')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\SMARTHOME\tinytuya-master\tinytuya\Cloud.py", line 217, in _tuyaplatform
    response = requests.get(url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shee.cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shee.cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 59, in request
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shee.cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\adapters.py", line 458, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "C:\Users\shee.cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\adapters.py", line 261, in cert_verify
    raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: 0

with this error
"python -m tinytuya wizard" does not run.

If I need to install the certificate separately, where should I do that?!

The "python -m tinytuya wizard" commands were working fine until a few days ago. Suddenly it doesn't work.

**Comment by billonariosh** [comment]
It was confirmed to be a firewall issue. I'll close this issue
