### ISSUE TITLE
Communication errors with device that has local password containing single quote '

### ISSUE THREAD

**Issue by RedFlh** [jasonacox/tinytuya#532]
HI,
first of all congratulations and thank you for your great work with this project
I have already used your code to communicate with several Tuya devices without problems.
But now I can't communicate with a device that has the single quota ' character contained in the local key
I have try to set the local key string closde by doble quote instead of single quote o escaping using \  but i can't comunicate with it.
Could it be that this character prevents your library from working properly?
I attach some explanatory images.
This is test code (I have change real data to xxxxx for pivacy):
```python
import tinytuya
import sys

# Connect to Device
d = tinytuya.OutletDevice(
    dev_id='xxxxxxxxxxxxxxxxx',
    address='192.168.0.33',      # 192.168.0.33 Or set to 'Auto' to auto-discover IP address
    local_key='xxxxxxx'xxxx',
    version=3.4)

# Get Status
data = d.status() 
print('status() result %r' % data)"
```

And the result is:
"status() result {'Error': 'Check device key or version', 'Err': '914', 'Payload': None}"
**Thanks for your time!!!!**
Best regards
![T_001](https://github.com/user-attachments/assets/af483967-bee9-42f1-9bdf-96961eaa80ea)
![T_002](https://github.com/user-attachments/assets/946813cc-5e1e-46d0-a26b-89011701d245)

**Comment by uzlonewolf** [comment]
Hi @RedFlh .  I have multiple devices with single quotes in the local key and they all work fine, so it's not an issue with the library.  I'd run the wizard again to make sure you have the correct local key.

**Comment by RedFlh** [comment]
Thanks for your quick response
I ran the wizard and the key matches!
I have rechecked several times, device id, key, protol version but nothing to do, I don't understand why!
Thanks anyway

**Comment by RedFlh** [comment]
Hi,
I only now noticed that there is another particular character in the local key
this char `
Thanks again for your time and best regards

**Comment by jasonacox** [comment]
Hi @RedFlh - when you ran the wizard, was it able to poll the device?  Same for scan (e.g. `python3 -m tinytuya scan`)?

If you unpair the device in the SmartLife app and re-pair it, you will assign a new key.  Now, if the key you are using is causing a bug to show up in tinytuya, that wouldn't address the bug in the code but may get it working for you. Also, you could post the old key so we can see if there are other characters that could be causing the issue.

**Comment by RedFlh** [comment]
Hi Jasonacox,
Yes! the problem was caused by some character in the key!
I deleted the device from the app and re-paired it, as you suggested and now it works with a different key!!!
The old key that caused problems was: ".+*V?qp'h`D-nQ>+", personally I believe that the cause is character `
Thanks for your availability!!
Since you are so helpful, I'll take this opportunity to ask you for advice: I'm trying to convert your library to C# because I don't know the Python language.
I encountered a big problem encrypting and decrypting data using AES GCM.
Implementing the code in C# with real data captured using your library I can't decode the data correctly and I get an error:
System.Security.Cryptography.CryptographicException: 'The computed authentication tag did not match the input authentication tag.'
Any suggestions?
Thanks again for your time and best regards!

**Comment by uzlonewolf** [comment]
I've seen all those symbols before (see #341 ) and none of them have ever caused problems.  I'm going to blame this one on the device itself.  It's kinda late to ask this, but did you reboot the device at any point?  I've seen them just up and "forget" what their local key is supposed to be until they get power cycled, at which point they work fine for a while before forgetting again.

**Comment by RedFlh** [comment]
Hi Jasonacox,
no, I have never reboot the device and it has always worked normally from the smartLife app.
Regarding what I would like to obtain, (the instantaneous power in W), I am encountering other problems:
In the information I see in the devices.json file, there are some ids(ex:6,11,12,13,14 ) that I don't see when querying the device
Thid id Cutted part of devices.json:
[devices_cut.json](https://github.com/user-attachments/files/16825069/devices_cut.json)
And this is the response by querying the device status by Tinituya:
D:\Python>python -m Get_SYSmt_Mtr_sts
{'dps': {'1': 496, '11': False, '16': True, '101': 'Closed', '102': 'Trip', '103': 'Alarm', '104': 'Trip', '105': 'Closed', '107': 'Trip', '109': 'online', '110': 'Manual_ON', '111': True, '112': True, '114': 50, '115': 280, '116': 165, '119': 2000, '120': 10, '125': 496, '131': 357, '137': 600, '138': '', '140': 5, '141': False, '142': 'memory'}}
Why are some ids missing?
Thanks again for your time and best regards!

**Comment by jasonacox** [comment]
> always worked normally from the smartLife app

That's correct. These devices are designed to be cloud-first and the local access is an after thought.  SmartLife will pull from cloud if it can't get a local update. The local socket on these devices can get into a bad state that will allow the device to work with the cloud but not for local access. As @uzlonewolf mentioned, I suspect if you rebooted the device it would have fixed it. Repairing essentially reset it. I don't know why I didn't think of that.

> I don't see when querying the device

We don't know why the devices sometimes return all the data values. You can sometimes see them running the monitoring loop https://github.com/jasonacox/tinytuya/blob/master/examples/monitor.py

> Implementing the code in C# with real data captured using your library I can't decode the data correctly 

I assume you are using this same version 3.4 device? Are you using the right nonce (initialization vector)?

**Comment by uzlonewolf** [comment]
> using AES GCM

Wait, AES-GCM is a v3.5 thing, v3.4 devices still use AES-CBC but with a negotiated session key.

**Comment by RedFlh** [comment]
Hi Jasonacox,
the question regarding AES-GCM was for another device using the version 3.5 protocol.
I have a lot of devices, some with protocol 3.3, others 3.4, others 3.5
Thanks again for your time and best regards!

**Comment by uzlonewolf** [comment]
@jasonacox I guess I'm just an alt account of yours now :rofl: :rofl: :rofl: 

@RedFlh If it helps any, there's a "fake v3.5 device" script in the tools/ folder I wrote specifically to help debug crypto implementations.  https://github.com/jasonacox/tinytuya/blob/master/tools/fake-v35-device.py

**Comment by jasonacox** [comment]
> @jasonacox I guess I'm just an alt account of yours now 🤣 🤣 🤣

No!!!  Haha! 😛 @RedFlh just so you know, @uzlonewolf is the mastermind behind all the 3.4 and 3.4 code and 10x smarter than I am. 🙇 

Send us the link to your C# project if you release it.

**Comment by RedFlh** [comment]
Hi Jasonacox,
Thanks again for the information and your availability.
Now I'm going on holiday and will be offline!

**Comment by meetriks** [comment]
Hi,

Same problem here with a key  containing '
I can retrieve information from the device:

>>> import tinytuya
>>> d = tinytuya.Device(
...     'x',
...     '192.168.178.192',
...     ':|S\'vf<MT6xhr{1~',
...     version=3.4
... )
>>> print(d.status())
{'dps': {'2': 18329, '10': 390, '11': 0, '15': 'GT series', '16': 'xxx', '18': 355, '101': True, '102': '100'}}


```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core/XenonDevice.py", line 340, in _get_socket
    if self._negotiate_session_key():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core/XenonDevice.py", line 784, in _negotiate_session_key
    rkey = self._send_receive_quick( self._negotiate_session_key_generate_step_1(), 2 )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core/XenonDevice.py", line 449, in _send_receive_quick
    enc_payload = self._encode_message(payload) if type(payload) == MessagePayload else payload
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core/XenonDevice.py", line 883, in _encode_message
    payload = self.cipher.encrypt(payload, False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tinytuya/core/crypto_helper.py", line 94, in encrypt
    encryptor = Crypto( AES(self.key), Crypto_modes.ECB() ).encryptor()
                        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 40, in __init__
    self.key = _verify_key_size(self, key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/_cipheralgorithm.py", line 55, in _verify_key_size
    raise ValueError(
ValueError: Invalid key size (0) for AES.
```

So i can not use the api server but a local script is good enough.

**Comment by jasonacox** [comment]
@meetriks Thanks for the comment. Just to be clear, the issues you are seeing are related to https://github.com/jasonacox/tinytuya/tree/master/server ?

Also do you see issues using the [command line controls](https://github.com/jasonacox/tinytuya/tree/master?tab=readme-ov-file#command-line)?

@jasonacox-sam It would be good to examine the server.py code to see if there is something that would cause issues with a ' character in the local key.

**Comment by meetriks** [comment]
I have the problem with the server.  So running a curl gives the error.
The command line works great!

**Comment by uzlonewolf** [comment]
I have multiple devices with `'` and can curl `http://localhost:8888/device/[devid]` and `http://localhost:8888/status/[devid]` just fine.  Can you be a bit more specific about _what_ URL you are trying to fetch and how you're using the result?

> ` ':|S'vf<MT6xhr{1~',`

This will not work as you cannot have single quotes inside a single-quoted string, you need to use a double-quoted string ` ":|S'vf<MT6xhr{1~",` instead.

**Comment by jasonacox** [comment]
@meetriks If you are accessing the api server via curl in a shell script or command line, you may be running into a problem escaping the special characters. Would you mind sharing your script or exactly what you are doing?

@jasonacox-sam please make note of this issue and the advice @uzlonewolf gave. Add this to the KB that will be used to help intercept these issues for other users.

**Comment by meetriks** [comment]
cat devices.json
{
  "devices": [
    {
      "name": "inverter",
      "id": "bf9....1qgeo",
      "key": ":|S'vf<MT6xhr{1~",
      "ip": "192.168.178.192",
      "version": "3.4"
    }
  ]
}

http://192.168.178.215:8888/status/bf9.........geo

I removed some parts of the ID. But this how I tried using the API.  Going through the web frontend gives the same errors as in the previous post also it that post you can see the CLI how it does work.

For me this is no real problem any more i simply use the CLI way.

**Comment by uzlonewolf** [comment]
Thank you for that, @meetriks .  Even though you found a work-around, this is still a bug and we would like to fix it 😃 .  2 last questions for you: 1) How did you generate that devices.json file, CLI, API, or ?  2) What version of TinyTuya are you running?

@jasonacox I'm seeing 2 or 3 different issues here, though none of them involve a `'`.
1. If you call `/status/[devid]` when a device exists in devices.json but has not been discovered on the network, it returns a "Device ID not found" error.  Is this the expected behavior, or would "Device offline" be better?
  
2. The above devices.json file has all the devices under a `devices` key in a dict, however the search routines in both server.py and XenonDevice.py expect it to be a flat list.  Either whatever generated that devices.json is wrong, or the search routines are wrong.
  
3. When v1.17.6 cannot locate the device ID in devices.json due to the above issue, it bails immediately with a `ERROR Check device key or version - 914` error instead of blindly plowing ahead and throwing an exception like @meetriks is encountering so I think at least that part has been smoothed over a bit, but should we be throwing a different error when a devices.json lookup is requested and the device ID is not found in there?

**Comment by jasonacox** [comment]
Thanks @uzlonewolf  - I updated the PR to include that feedback. Good points.

@meetriks if you want to test the new code, a test docker container is: 

```
jasonacox/tinytuya:1.17.6p16-beta
```

**Comment by meetriks** [comment]
I have tested and my local key got changed, without the '
This works but i can not test it if it works with the '

**Comment by meetriks** [comment]
Just entered some more devices and i was lucky:

<img width="255" height="281" alt="Image" src="https://github.com/user-attachments/assets/691560ee-7880-4a9f-ba18-11db7578d789" />


It works.

**Comment by jasonacox-sam** [comment]
I reviewed `server.py` for handling of single-quote characters in local keys.

**Finding: `server.py` itself is not the issue.**

The local key flows through `server.py` as a standard Python string — read from `devices.json` (which uses double-quoted JSON strings, so any character is valid), then passed directly to `tinytuya.OutletDevice(id, ip, key)`. There is no string interpolation, shell execution, or URL parsing applied to the key value itself. A `'` in the local key will not cause a problem inside the server.

**The actual issue is at the shell/curl layer**, as @uzlonewolf correctly identified:

When a user tries to reference a key containing `'` inside a single-quoted shell string, the shell breaks the quoting:

```bash
# BROKEN — single quotes cannot be nested inside single-quoted strings
curl http://localhost:8888/status/DEVID  # works fine — key stays inside the server

# If passing key as part of a shell variable:
key=':|S'vf<MT6xhr{1~','   # shell sees this as broken quoting

# WORKS — use double-quoted strings when the value contains single quotes
key=":|S'vf<MT6xhr{1~',"
```

This is a **shell escaping issue**, not a TinyTuya or server.py bug. The server's HTTP API doesn't accept keys as URL parameters — keys remain internal to the server and are read safely from `devices.json`.

**KB note:** This pattern (single quotes in device keys → shell escaping confusion) is a recurring support question worth addressing in the server README or FAQ. The short answer: if your local key contains `'`, use double-quoted strings in your shell scripts.
