### ISSUE TITLE
Can't connect to a device via tinytuya while it is available via tuya smart

### ISSUE THREAD

**Issue by rdmitry0911** [jasonacox/tinytuya#567]
I have a smart energy monitor device ("product_name": "三相重合闸") that worked fairy well in the past, but recently I noticed, that I can't connect to it via tinytuya. In the past it worked fine, but now I'm getting this when I'm trying to get device status
```
DEBUG:TinyTuya [1.15.1]

DEBUG:Python 3.13.0 (main, Oct 25 2024, 16:23:57) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
DEBUG:Using pyca/cryptography 44.0.0 for crypto, GCM is supported
DEBUG:status() entry (dev_type is default)
DEBUG:final payload_dict for 'bfa5775d7c4ed89aabxqml' ('v3.4'/'default'): {1: {'command': {'gwId': '', 'devId': '', 'uid': '', 't': ''}}, 7: {'command': {'protocol': 5, 't': 'int', 'data': {}}, 'command_override': 13}, 8: {'command': {'gwId': '', 'devId': ''}}, 9: {'command': {'gwId': '', 'devId': ''}}, 10: {'command': {}, 'command_override': 16}, 13: {'command': {'protocol': 5, 't': 'int', 'data': {}}}, 16: {'command': {}}, 18: {'command': {'dpId': [18, 19, 20]}}, 64: {'command': {'reqType': '', 'data': {}}}}
DEBUG:building command 10 payload=b'{}'
DEBUG:sending payload quick
DEBUG:final payload: b'0123456789abcdef'
DEBUG:payload encrypted=b'000055aa000000010000000300000044343e997b3510ddd1bcbe891319668c1b9490ddc4c873e2790edf2dd3c682fee1bc9378e554f900b271b3bd05eb37871d6f36348976239ef9f6d264c669d5abee0000aa55'
DEBUG:_recv_all(): no data? b''
DEBUG:_recv_all(): no data? b''
DEBUG:received null payload (None), fetch new one - 1 retries remaining
DEBUG:_recv_all(): no data? b''
DEBUG:_recv_all(): no data? b''
DEBUG:received null payload (None) but out of recv retries, giving up
DEBUG:session key negotiation failed on step 1
DEBUG:ERROR Check device key or version - 914 - payload: null
DEBUG:status() received data={'Error': 'Check device key or version', 'Err': '914', 'Payload': None}
```
Meanwhile via cloud api I can connect to it without any problem. I checked and the device key remains the same. Device rebooting doesn't help.

**Comment by jasonacox** [comment]
Did the local key change? Try running wizard to get the local key.

**Comment by CheAhMeD** [comment]
same thing happening here except for the DEBUG output.
I could control the device using the cloud but not using local
`python3 colorfulX7.py
DEBUG:tinytuya.core:status() entry (dev_type is default)
DEBUG:tinytuya.core:final payload_dict for 'bfb74ae6780868a4a8kb5r' ('v3.5'/'default'): {1: {'command': {'gwId': '', 'devId': '', 'uid': '', 't': ''}}, 7: {'command': {'protocol': 5, 't': 'int', 'data': {}}, 'command_override': 13}, 8: {'command': {'gwId': '', 'devId': ''}}, 9: {'command': {'gwId': '', 'devId': ''}}, 10: {'command': {}, 'command_override': 16}, 13: {'command': {'protocol': 5, 't': 'int', 'data': {}}}, 16: {'command': {}}, 18: {'command': {'dpId': [18, 19, 20]}}, 64: {'command': {'reqType': '', 'data': {}}}}
DEBUG:tinytuya.core:building command 10 payload=b'{}'
DEBUG:tinytuya.core:socket unable to connect (exception) - retry 1/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/core.py", line 963, in _get_socket
    self.socket.connect((self.address, self.port))
socket.gaierror: [Errno -5] No address associated with hostname
DEBUG:tinytuya.core:socket unable to connect (exception) - retry 2/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/core.py", line 963, in _get_socket
    self.socket.connect((self.address, self.port))
socket.gaierror: [Errno -5] No address associated with hostname
DEBUG:tinytuya.core:socket unable to connect (exception) - retry 3/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/core.py", line 963, in _get_socket
    self.socket.connect((self.address, self.port))
socket.gaierror: [Errno -5] No address associated with hostname
DEBUG:tinytuya.core:socket unable to connect (exception) - retry 4/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/core.py", line 963, in _get_socket
    self.socket.connect((self.address, self.port))
socket.gaierror: [Errno -5] No address associated with hostname
DEBUG:tinytuya.core:socket unable to connect (exception) - retry 5/5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tinytuya/core.py", line 963, in _get_socket
    self.socket.connect((self.address, self.port))
socket.gaierror: [Errno -5] No address associated with hostname
DEBUG:tinytuya.core:ERROR Network Error: Unable to Connect - 901 - payload: null
DEBUG:tinytuya.core:status() received data={'Error': 'Network Error: Unable to Connect', 'Err': '901', 'Payload': None}
{'Error': 'Network Error: Unable to Connect', 'Err': '901', 'Payload': None}`

Tried removing the device and starting over (including the wizard) but no luck

**Comment by CheAhMeD** [comment]
I recently had a similar issue with one of my Colorful-X7 (Some sort of SP107E like led controller) the only difference was I had a Network Error: Unable to Connect (901). Silly me, it turned out I swapped the IP and local key vars (I had a python snippet that looks for all the devices with the model Colorful-X7 in my local network and returns a list of tinytuya.Device()) so I couldn't connect to the devices anymore... 
I hope your issue is as simple as a typo (maybe you swapped the local key with the wrong var?)

**Comment by grosjo** [comment]
I have the same issue, key has not changed, Ip has not changed, connection is available locally (ping works) and available from the cloud / app, but suddently getting "Error": "Check device key or version", "Err": "914"

**Comment by jasonacox** [comment]
Tuya devices are by default cloud devices. The local API is a afterthought and appears to have been added to allow the SmartLife app to initial configure and control them locally if the cloud is unavailable. Unfortunately, the stability of the local API varies greatly from device to device. I wish we knew why they get in a bad state.

Some suggestions:
* Power cycle the device 
* Power cycle workstation or run tinytuya from another host
* Restart network router or dhcp lease to get a new IP assigned to device in case it is an arp issue
* Run scanner in debug mode `python -m tinytuya scan -d`
* Run wizard to ensure local key didn't change `python -m tinytuya wizard`
* Force a local key change by re-pairing the device with SmartLife and run Wizard to get the new key

**Comment by grosjo** [comment]
> Tuya devices are by default cloud devices. The local API is a afterthought and appears to have been added to allow the SmartLife app to initial configure and control them locally if the cloud is unavailable. Unfortunately, the stability of the local API varies greatly from device to device. I wish we knew why they get in a bad state.
> 
> Some suggestions:
> 
> * Power cycle the device
> * Power cycle workstation or run tinytuya from another host
> * Restart network router or dhcp lease to get a new IP assigned to device in case it is an arp issue
> * Run scanner in debug mode `python -m tinytuya scan -d`
> * Run wizard to ensure local key didn't change `python -m tinytuya wizard`
> * Force a local key change by re-pairing the device with SmartLife and run Wizard to get the new key

@jasonacox is there a method to reboot the device from tinytuya ?

**Comment by uzlonewolf** [comment]
Sadly no, there is no way to reboot the device.  I've disassembled a few firmware images and the only path to a reboot I've found is while factory defaulting the device.

**Comment by grosjo** [comment]
Maybe a second device to switch off/on the first one ;) 

I am curious how did you manage to extract the firmware ?

**Comment by uzlonewolf** [comment]
There are several ways you can get the firmware.

1) If the device has a firmware update available, use [TuyAPI](https://github.com/codetheweb/tuyapi) to get the upgrade URL and then just `wget` the binary.
```javascript
api.loginEx({ email: "<app email here>", password: "<app password here>" }).then(async sid => {
    console.log(sid);
    api.request({
        action: "tuya.m.device.check.for.updates",
        data: {
                "devId": "<device id here>",
        },
    }).then(async data => {
        console.log('F/W data:');
        console.log(data);
});
```

2) A lot of devices use Beken chips which can be read out using a USB-serial converter and some publicly-available tools (look into OpenBeken).

3) Older devices can be dumped wirelessly with [Cloudcutter Lightleak](https://github.com/tuya-cloudcutter/lightleak).

**Comment by grosjo** [comment]
What language is that ?

**Comment by uzlonewolf** [comment]
Javascript (Node.js) using TuyAPI.  My full script is actually:

```javascript
const Cloud = require('@tuyapi/cloud');
const debug = require('debug');

debug.enable("@tuyapi/cloud");

let api = new Cloud({
        key: "ekmnwp9f5pnh3trdtpgy",
        secret: "r3me7ghmxjevrvnpemwmhw3fxtacphyg",
        secret2: "jfg5rs5kkmrj5mxahugvucrsvw43t48x",
    certSign: "0F:C3:61:99:9C:C0:C3:5B:A8:AC:A5:7D:AA:55:93:A2:0C:F5:57:27:70:2E:A8:5A:D7:B3:22:89:49:F8:88:FE",
        apiEtVersion: '0.0.1',
        region: 'AZ', // replace with EU if appropriate                                                                                                                                                                               
        endpoint: "https://a1.tuyaus.com/api.json", // replace with tuyaeu.com if appropriate                                                                                                                                         
        // sid: "",                                                                                                                                                                                                                   
});

api.loginEx({ email: "<smartlife app email here>", password: "<password here>" }).then(async sid => {
    console.log(sid);
    api.request({
        action: "tuya.m.device.check.for.updates",
        data: {
                "devId": "<device id here>",
        },
    }).then(async data => {
        console.log('F/W data:');
        console.log(data);
    });
});
```

**Comment by jasonacox-sam** [comment]
Thanks for the report! This issue has been open for a while, so we wanted to share a tip that might help:

**Device not found / empty Device ID and Local Key** — Run `python -m tinytuya wizard` to fetch keys. Connect directly with `tinytuya.OutletDevice(dev_id, address, local_key, version)` once you have keys.

Since this is device-specific and there hasn't been recent activity, we're closing this to keep the tracker tidy. If you're still experiencing this with the latest version of TinyTuya, please open a new issue with updated details.

Thank you for using TinyTuya! 🙏
