### ISSUE TITLE
Scan failed when color=False

### ISSUE THREAD

**Issue by goooroooX** [jasonacox/tinytuya#63]
TinyTuya (Tuya device scanner) [1.2.7]

Scanning on UDP ports 6666 and 6667 for devices (10 retries)...

Traceback (most recent call last):
  File "run.py", line 45, in <module>
    tinytuya.scan(max_retries, color)
  File "d:\Downloads\TinyTuya\libs\tinytuya\__init__.py", line 1629, in scan
    d = deviceScan(True, maxretry, color)
  File "d:\Downloads\TinyTuya\libs\tinytuya\__init__.py", line 1792, in deviceScan
    normal, version, dim, productKey, note, subbold, ip, cyan, gwId, red, dkey, yellow, version))
UnboundLocalError: local variable 'cyan' referenced before assignment

**Comment by jasonacox** [comment]
Good find!  Updated code for fix in v1.2.9.
